/*contains level number, difficulty, relevant dot colors, answer key, and steps for each level displayed*/
const LevelData = [
    {
        id: 1,
        difficulty: "EASY",
        need: "3 LIGHT BLUE, 2 GREEN, 1 ORANGE, 2 TEAL, AND 1 GOLD",
        answer1: "lightblue",
        answer2: "lightblue",
        answer3: "lightblue",
        answer4: "green",
        answer5: "gold",
        answer6: "orange",
        answer7: "green",
        answer8: "teal",
        answer9: "teal",
        steps: ["The two green cubes are on the left.", "The two teal cubes are at the bottom.", "The three light blue cubes are at the top.", "The orange cube is on the right."],

        
    },
    {
        id: 2,
        difficulty: "EASY",
        need: "1 YELLOW, 2 LIGHT BLUE, 3 ORANGE, 2 PURPLE, AND 1 GOLD",
        answer1: "lightblue",
        answer2: "yellow",
        answer3: "gold",
        answer4: "orange",
        answer5: "orange",
        answer6: "orange",
        answer7: "lightblue",
        answer8: "purple",
        answer9: "purple",
        steps: ["The yellow cube is at the top in the middle.", "The three orange cubes are in the same row.", "The two purple cubes touch each other.", "The two light blue cubes are on the left. They do not touch each other."],

    },
    {
        id: 3,
        difficulty: "EASY",
        need: "2 YELLOW, 1 LIGHT BLUE, 2 GREEN, 1 ORANGE, 2 TEAL, AND 1 GOLD",
        answer1: "orange",
        answer2: "teal",
        answer3: "lightblue",
        answer4: "gold",
        answer5: "teal",
        answer6: "yellow",
        answer7: "green",
        answer8: "green",
        answer9: "yellow",
        steps: ["The two green cubes are at the bottom.", "The two yellow cubes are on the right.", "A teal cube is precisely in the middle.", "The orange cube is in a corner.", "The light blue cube is directly above the two yellow cubes.", "One teal cube touches the light blue cube."],

    },
    {
        id: 4,
        difficulty: "MEDIUM",
        need: "1 PINK, 2 YELLOW, 1 ORANGE, 2 DARK BLUE, 2 GREY, AND 1 GOLD",
        answer1: "darkblue",
        answer2: "gold",
        answer3: "yellow",
        answer4: "pink",
        answer5: "orange",
        answer6: "yellow",
        answer7: "darkblue",
        answer8: "grey",
        answer9: "grey",
        steps: ["The orange cube is below the golden cube. They touch each other.", "The pink cube is above a dark blue cube. They touch each other.", "The two grey cubes touch each other.", "A dark blue cube is above the pink cube. They touch each other.", "The yellow cubes are in the column to the right. They touch each other.", "The golden cube touches precisely three other cubes."],
    },
    {
        id: 5,
        difficulty: "HARD",
        need: "3 LIGHT BLUE, 3 ORANGE, 2 TEAL, AND 1 GOLD",
        answer1: "teal",
        answer2: "orange",
        answer3: "lightblue",
        answer4: "orange",
        answer5: "gold",
        answer6: "lightblue",
        answer7: "teal",
        answer8: "orange",
        answer9: "lightblue",
        steps: ["The golden cube touches three orange cubes.", "Each teal cube touches two orange cubes.", "There is an orange cube in every row.", "In the left column there is one orange cube.", "In the right column there are no orange cubes at all."],
    },
    {
        id: 6,
        difficulty: "HARD",
        need: "3 YELLOW, 3 GREEN, 2 TEAL, AND 1 GOLD",
        answer1: "yellow",
        answer2: "green",
        answer3: "gold",
        answer4: "teal",
        answer5: "yellow",
        answer6: "green",
        answer7: "green",
        answer8: "teal",
        answer9: "yellow",
        steps: ["There is one teal cube in the left column.", "In each row and column there is exactly one green cube.", "In each row and column there is exactly one yellow cube.", "The golden cube touches two green cubes, but does not touch any yellow cubes at all.", "There is one teal cube in the bottom row."],
    }
]

export default LevelData